// Capability detection: which browser data categories can be read, backed up
// and restored via public extension APIs in the current browser. This module
// is the single source of truth for the capability report and the UI.
//
// Restore levels:
//   'full'    - restore via public API, faithful to backup (documented deltas listed in notes)
//   'partial' - restore possible but approximate / lossy (documented in notes)
//   false     - cannot be restored via public API (documented in notes)

import { hasCompressionStream } from './util.js';

const has = (ns) => typeof chrome !== 'undefined' && chrome[ns] !== undefined && chrome[ns] !== null;

export function getChromeVersion() {
  const m = navigator.userAgent.match(/Chrom(?:e|ium)\/(\d+(\.\d+)+)/);
  return m ? m[1] : 'unknown';
}

export function getPlatformInfo() {
  try {
    return chrome.runtime.getPlatformInfo();
  } catch (e) {
    return null;
  }
}

// Static, API-presence-based capability map. Runtime probes may refine notes.
export function detect() {
  const caps = {};

  caps.bookmarks = {
    available: has('bookmarks'),
    canRead: has('bookmarks'),
    canBackup: has('bookmarks'),
    canRestore: has('bookmarks') ? 'full' : false,
    notes: has('bookmarks')
      ? [
          'Tree hierarchy, titles, URLs and per-folder order are preserved.',
          'dateAdded timestamps are NOT restored: bookmarks.create() accepts only parentId/index/title/url (verified by runtime probe).',
        ]
      : [],
  };

  caps.history = {
    available: has('history'),
    canRead: has('history'),
    canBackup: has('history'),
    canRestore: has('history') ? 'partial' : false,
    notes: [
      'Full read access: items (visitCount, typedCount, lastVisitTime) + per-URL visit list (timestamps, transition types).',
      'BASIC restore only via chrome.history.addUrl() (verified working by runtime probe): URLs are re-registered in history, but as a single "typed" visit at restore time. Original titles, visit counts, visit timestamps and transition types cannot be restored — no API exists for them.',
      'Full-fidelity history data (incl. per-visit details) is preserved inside the backup file for archival.',
    ],
  };

  caps.tabsWindows = {
    available: has('tabs') && has('windows'),
    canRead: has('tabs') && has('windows'),
    canBackup: has('tabs') && has('windows'),
    canRestore: has('tabs') && has('windows') ? 'full' : false,
    notes: [
      'Window type, state and geometry; tab URLs, order, pinned and muted state are restored.',
      'Tab titles and favicons are re-fetched by the browser (no API to set a tab title).',
      'Incognito windows are excluded from backup by design (privacy boundary).',
      'chrome:// URLs are restored best-effort; a few internal pages may be refused by the browser.',
    ],
  };

  caps.tabGroups = {
    available: has('tabGroups'),
    canRead: has('tabGroups'),
    canBackup: has('tabGroups'),
    canRestore: has('tabGroups') ? 'full' : false,
    notes: [
      'Group title, color and collapsed state are restored via tabs.group() + tabGroups.update().',
      'Group IDs are regenerated by the browser on restore (mapping old->new done internally).',
    ],
  };

  caps.sessions = {
    available: has('sessions'),
    canRead: has('sessions'),
    canBackup: has('sessions'),
    canRestore: has('sessions') ? 'partial' : false,
    notes: [
      'getRecentlyClosed() exposes at most 25 most-recently-closed sessions (API limit MAX_SESSION_RESULTS=25).',
      'sessions.restore() can only reopen the single most recently closed item, so restore re-opens backed-up tabs/windows as NEW tabs/windows (URLs preserved, timestamps and back/forward history are not).',
    ],
  };

  caps.cookies = {
    available: has('cookies'),
    canRead: has('cookies'),
    canBackup: has('cookies'),
    canRestore: has('cookies') ? 'full' : false,
    notes: [
      'Requires broad host permissions. All attributes restored: value, domain, path, secure, httpOnly, sameSite, expirationDate, hostOnly.',
      'Partitioned (CHIPS) cookies: invisible to plain getAll() and there is no partition-key enumeration API — the collector scans candidate keys derived from tabs/history/reading list. Backup of CHIPS cookies is therefore best-effort.',
      'Partitioned cookies CAN be re-created with cookies.set() when partitionKey includes hasCrossSiteAncestor:false (probe-verified on Chromium 131); they are restored into their original partition.',
      'Incognito cookie store excluded by design.',
    ],
  };

  caps.downloads = {
    available: has('downloads'),
    canRead: has('downloads'),
    canBackup: has('downloads'),
    canRestore: has('downloads') ? 'partial' : false,
    notes: [
      'Only download METADATA is accessible (url, filename, size, times, state). File bytes are NOT accessible via any extension API.',
      'Optional restore mode re-downloads items from their source URL (needs network, produces new timestamps); disabled by default.',
    ],
  };

  caps.readingList = {
    available: has('readingList'),
    canRead: has('readingList'),
    canBackup: has('readingList'),
    canRestore: has('readingList') ? 'full' : false,
    notes: [
      'Requires Chrome/Chromium >= 114.',
      'URL, title and hasBeenRead flag are restored; creationTime/lastUpdateTime are assigned by the browser on add (no API to set them).',
    ],
  };

  caps.extensionStorage = {
    available: has('storage'),
    canRead: has('storage'),
    canBackup: has('storage'),
    canRestore: has('storage') ? 'full' : false,
    notes: [
      "This is THIS extension's own storage.local/storage.sync (e.g. its saved preferences), not website site-data.",
    ],
  };

  caps.installedExtensions = {
    available: has('management'),
    canRead: has('management'),
    canBackup: has('management'),
    canRestore: false,
    notes: [
      'Metadata only (name, version, enabled, permissions). Extension packages (.crx files) are NOT readable via any API.',
      'Restore is impossible via public API — the backup contains a checklist for manual reinstallation.',
    ],
  };

  caps.extensionPermissions = {
    available: has('permissions'),
    canRead: has('permissions'),
    canBackup: has('permissions'),
    canRestore: 'partial',
    notes: [
      "Only THIS extension's granted permissions/origins. Recorded for reference; re-granting requires an explicit user prompt.",
    ],
  };

  // Categories that exist in a browser but are NOT accessible via any public
  // extension API. Kept here so the capability report is honest about them.
  caps.browserSettings = {
    available: false,
    canRead: false,
    canBackup: false,
    canRestore: false,
    notes: [
      'Homepage, startup pages, search engines, theme, UI prefs: NO public API (chrome.settingsPrivate is Google-private and unavailable to normal extensions).',
    ],
  };

  caps.siteData = {
    available: has('debugger') && has('scripting'),
    canRead: has('debugger') && has('scripting'),
    canBackup: has('debugger') && has('scripting'),
    canRestore: has('debugger') && has('scripting') ? 'full' : false,
    notes: [
      "Websites' localStorage, IndexedDB (incl. schema, binary values, key generators), Cache Storage (byte-level bodies), Service Workers, OPFS and Storage Buckets — for EVERY origin (derived from tabs/history/bookmarks/reading list/cookies), not just open tabs.",
      'Method: chrome.debugger attaches to a tab per origin and executes page-context JavaScript (Runtime.evaluate); the CDP DOMStorage/IndexedDB/ServiceWorker domains are blocked through chrome.debugger (research-proven on Chrome 153), page-context execution is the only working path.',
      'While running, Chrome shows its "started debugging" infobar and one hidden tab per origin is opened and closed — inherent to the CDP path.',
      'Data crosses the debugger boundary as chunked JSON (ASCII-safe), which also sidesteps the proven lone-surrogate corruption of the debugger transport.',
      'Known restore limits: sessionStorage is content-only (per-tab semantics); Service Worker re-registration requires the worker script to still be served by its site; partitioned (third-party iframe) storage restores only into currently-open embedding pages.',
    ],
  };

  caps.partitionedStorage = {
    available: has('scripting'),
    canRead: has('scripting'),
    canBackup: has('scripting'),
    canRestore: has('scripting') ? 'partial' : false,
    notes: [
      'Storage of cross-origin iframes, partitioned per top-level site (localStorage/IndexedDB/CacheStorage). Read and written via chrome.scripting allFrames injection — the debugger cannot reach OOPIF frames.',
      'Backup covers the frames of currently-open tabs (that is where partitioned storage exists and can be enumerated).',
      'Restore requires the embedding top-level page to be open; partitions without a live host page are kept in the backup with an explicit note (no fragile page reconstruction).',
      'CHIPS partitioned cookies are handled by the cookies category, not here.',
    ],
  };

  caps.opfs = {
    available: has('debugger'),
    canRead: has('debugger'),
    canBackup: has('debugger'),
    canRestore: has('debugger') ? 'full' : false,
    notes: [
      'Origin Private File System: nested directories, unicode/special filenames, empty files, binary content — read and restored byte-level via page-context execution (experimentally verified on Chrome 153, research/opfs-buckets).',
      'File contents, sizes and directory structure are exact; per-file lastModified is re-stamped on restore (no API to set it) — intentionally lossy metadata.',
    ],
  };

  caps.storageBuckets = {
    available: has('debugger'),
    canRead: has('debugger'),
    canBackup: has('debugger'),
    canRestore: has('debugger') ? 'full' : false,
    notes: [
      'Storage Buckets: bucket-scoped IndexedDB, bucket-scoped Cache Storage and bucket-scoped OPFS are all backed up and restored (verified on Chrome 153; the official doc claims only IndexedDB is implemented — empirical probing found all three).',
      'Bucket identity is the name string; durability/persisted are request hints at open() and are NOT echoed back by the API (durability reads null). Bucket names cannot start with "__" (browser restriction).',
      "clearDataForOrigin 'all' deletes buckets (verified) — wipe policy must recreate them from the backup.",
    ],
  };

  caps.passwordsAutofill = {
    available: false,
    canRead: false,
    canBackup: false,
    canRestore: false,
    notes: ['Passwords, autofill, payment methods: no public API and explicitly out of scope for security reasons.'],
  };

  caps.favicons = {
    available: false,
    canRead: true,
    canBackup: false,
    canRestore: false,
    notes: [
      'Favicons are re-fetched automatically after restore; backing up the image cache adds size with zero restorable value (derived data).',
    ],
  };

  caps.topSites = {
    available: has('topSites'),
    canRead: has('topSites'),
    canBackup: false,
    canRestore: false,
    notes: ['Derived ranking from history; covered by the history backup. Not separately backed up.'],
  };

  caps.contentSettings = {
    available: has('contentSettings'),
    canRead: has('contentSettings'),
    canBackup: false,
    canRestore: false,
    notes: [
      'Per-site content settings (site permissions): chrome.contentSettings can SET patterns but cannot reliably ENUMERATE existing exceptions, so a faithful backup is impossible. Not implemented; documented.',
    ],
  };

  return caps;
}

// Runtime probes: verify claims by experiment (used by "Check Capabilities" and
// by the automated test suite). Probes create temporary data and clean up after
// themselves. Never probes real user credentials.
// eslint-disable-next-line complexity -- TECH DEBT: complexity 43, refactoring risks behavior change
export async function runProbes() {
  const probes = {};

  // 1. Does bookmarks.create() honor dateAdded? (expected: NO)
  if (has('bookmarks')) {
    let accepted;
    let folderId = null;
    let bmId = null;
    try {
      const folder = await chrome.bookmarks.create({ parentId: '2', title: '__bbr_probe_' + Date.now() });
      folderId = folder.id;
      const fakeDate = 1000; // 1970-01-01, obviously not "now"
      const bm = await chrome.bookmarks.create({
        parentId: folderId,
        title: 'probe',
        url: 'https://bbr-probe.example/',
        dateAdded: fakeDate,
      });
      bmId = bm.id;
      accepted = bm.dateAdded === fakeDate;
    } catch (e) {
      accepted = 'throws: ' + (e.message || 'error');
    } finally {
      try {
        if (folderId) await chrome.bookmarks.removeTree(folderId);
      } catch (e) {
        /* ignore */
      }
      try {
        if (bmId) await chrome.bookmarks.remove(bmId);
      } catch (e) {
        /* ignore */
      }
    }
    probes.bookmarksCreateHonorsDateAdded = accepted;
  }

  // 2. Does chrome.history have any write API? (addUrl appeared in recent Chrome!)
  if (has('history')) {
    probes.historyWriteApis = {
      addUrl: typeof chrome.history.addUrl,
      addVisit: typeof chrome.history.addVisit,
      createDetails: typeof chrome.history.createDetails,
      knownMethods: Object.keys(chrome.history).sort(),
    };
    if (typeof chrome.history.addUrl === 'function') {
      let addUrlResult;
      const probeUrl = 'https://bbr-probe.example/bbr-history-probe';
      try {
        await chrome.history.addUrl({ url: probeUrl });
        const found = await chrome.history.search({ text: 'bbr-history-probe', startTime: 0, maxResults: 10 });
        const hit = found.find((h) => h.url === probeUrl);
        const visits = hit ? await chrome.history.getVisits({ url: probeUrl }) : [];
        addUrlResult = {
          works: !!hit,
          visitCount: hit ? hit.visitCount : null,
          title: hit ? hit.title : null,
          lastVisitTimeSet: hit ? hit.lastVisitTime : null,
          transition: visits[0] ? visits[0].transition : null,
        };
      } catch (e) {
        addUrlResult = { works: false, error: e.message || String(e) };
      } finally {
        try {
          await chrome.history.deleteUrl({ url: probeUrl });
        } catch (e) {
          /* ignore */
        }
      }
      probes.historyAddUrl = addUrlResult;
    }
  }

  // 2b. Reading list: dump actual API surface.
  if (has('readingList')) {
    probes.readingListApi = Object.keys(chrome.readingList).sort();
  }

  // 3. Does cookies support CHIPS partitionKey? (Chrome >= 119; CHIPS requires Secure)
  if (has('cookies')) {
    let partitioned;
    try {
      const details = {
        url: 'https://bbr-probe.example/',
        name: '__bbr_probe',
        value: '1',
        secure: true,
        partitionKey: { topLevelSite: 'https://bbr-probe.example/' },
      };
      const c = await chrome.cookies.set(details);
      if (c) {
        partitioned = { works: true, partitionKeyEcho: c.partitionKey ?? null };
        try {
          await chrome.cookies.remove({
            name: '__bbr_probe',
            url: 'https://bbr-probe.example/',
            partitionKey: { topLevelSite: 'https://bbr-probe.example/' },
          });
        } catch (e) {
          /* ignore */
        }
      } else {
        // Retry variant with hasCrossSiteAncestor (required by some CDP/API builds).
        try {
          const c2 = await chrome.cookies.set({
            url: 'https://bbr-probe.example/',
            name: '__bbr_probe',
            value: '1',
            secure: true,
            partitionKey: { topLevelSite: 'https://bbr-probe.example/', hasCrossSiteAncestor: false },
          });
          if (c2) {
            partitioned = {
              works: true,
              variant: 'hasCrossSiteAncestor:false',
              partitionKeyEcho: c2.partitionKey ?? null,
            };
            try {
              await chrome.cookies.remove({
                name: '__bbr_probe',
                url: 'https://bbr-probe.example/',
                partitionKey: { topLevelSite: 'https://bbr-probe.example/' },
              });
            } catch (e) {
              /* ignore */
            }
          } else {
            partitioned = {
              works: false,
              error: 'cookies.set resolved null (browser refused a partitioned cookie via the extension API)',
            };
          }
        } catch (e2) {
          partitioned = { works: false, error: e2.message || String(e2) };
        }
      }
    } catch (e) {
      partitioned = { works: false, error: e.message || String(e) };
    }
    probes.cookiesPartitionKey = partitioned;
    try {
      const testCookie = await chrome.cookies.set({
        url: 'https://bbr-probe.example/',
        name: '__bbr_plain',
        value: 'x',
      });
      probes.cookiesFirstPartyDomainField = testCookie && 'firstPartyDomain' in testCookie;
      try {
        await chrome.cookies.remove({ url: 'https://bbr-probe.example/', name: '__bbr_plain' });
      } catch (e) {
        /* ignore */
      }
    } catch (e) {
      probes.cookiesFirstPartyDomainField = 'error';
    }
  }

  // 4. Reading list round-trip: is creationTime honored on addEntry?
  if (has('readingList') && typeof chrome.readingList.getEntries === 'function') {
    let result = null;
    const urls = [];
    try {
      const url = 'https://bbr-probe.example/article-' + Date.now();
      urls.push(url);
      const fakeTime = 1000;
      try {
        await chrome.readingList.addEntry({
          url,
          title: 'probe',
          hasBeenRead: false,
          creationTime: fakeTime,
          lastUpdateTime: fakeTime,
        });
      } catch (e) {
        await chrome.readingList.addEntry({ url, title: 'probe', hasBeenRead: false });
      }
      const list = await chrome.readingList.getEntries({});
      const found = list.find((x) => x.url === url);
      if (found) result = { creationTimeHonored: found.creationTime === fakeTime, fields: Object.keys(found).sort() };
    } catch (e) {
      result = 'error: ' + (e.message || 'unknown');
    } finally {
      for (const u of urls) {
        try {
          await chrome.readingList.removeEntry({ url: u });
        } catch (e) {
          /* ignore */
        }
      }
    }
    probes.readingList = result;
  }

  // 5. CompressionStream availability (used to shrink backups).
  probes.compressionStream = hasCompressionStream();

  // 6. Private/restricted APIs that people sometimes hope for.
  probes.privateApisPresent = {
    settingsPrivate: has('settingsPrivate'),
    developerPrivate: has('developerPrivate'),
    enterprisePlatformKeysPrivate: has('enterprise.platformKeysPrivate'),
    contentSettings: has('contentSettings'),
    browsingData: has('browsingData'),
  };

  // 7. Sessions: confirm the 25-item limit constant.
  if (has('sessions')) {
    probes.sessionsMaxResults = chrome.sessions.MAX_SESSION_RESULTS || null;
  }

  return probes;
}
